### ISSUE TITLE
[BUG] CircleCI img not found

### ISSUE THREAD

**Issue by ETtestim** [yonatanmgr/opensource-il-site#33] opened 2023-05-05 11:27 UTC
CircleCI img not found.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/109076747/236445537-6cbe6adf-1690-40ae-abe4-6a2ab8261041.png">

reproduce:
1. enter bit.
2. see the img broken.
3. Also in devtools there is this error
<img width="557" alt="image" src="https://user-images.githubusercontent.com/109076747/236446055-471fc365-b23e-47c7-8858-6a8cc7e0a88a.png">

**Comment by yonatanmgr** [comment] 2023-05-06 16:49
About the issue itself - do you think the problem is on our end? `401` is an auth error and I'm pretty certain `500` is an error on `https://ga-beacon.appspot.com/`'s side. 
In any way - I'll be glad to add something like Playwright! Do you want to help with that?

**Comment by yonatanmgr** [comment] 2023-05-08 12:02
Closing for now as I don't think it's a problem on our end. About Playwright - @ETtestim you're welcome to open a separate issue for that 😉

**Closed by yonatanmgr** 2023-05-08 12:02 UTC
